apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app
  labels:
    app: python-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: python-app
  template:
    metadata:
      labels:
        app: python-app
    spec:
      containers:
      - name: python-container
        image: your-dockerhub-username/python-app:latest # <-- replace with your image
        ports:
        - containerPort: 5000 # Assuming your Python app runs on port 5000
